schemes/_dreamwidth.tt
-- site.root / site.imgroot, etc, change depending on whether you have
https root or not, so no need for this extra logic
=> Tweak logo path to be ready for https

htdocs/scss/skins/tropo/tropo-purple.scss
This reproduces the background effect from the pre-Foundation version.  Fixes dreamwidth/dw-free#1194.
=> [dw-free:#1194] Add background-color to footer in tropo-purple

styles/sundaymorning/layout.s2, styles/transmogrified/layout.s2
Changes the display type of the icon from inline to block,
which removes the extra whitespace added automatically for
baseline alignment. The layouts affected were:
-Sunday Morning
-Transmogrified
Fixes #1391
=> Removes whitespace below icons for dw-nonfree layouts

bin/upgrading/en_DW.dat, etc/config-local.pl, etc/staff.yaml, htdocs/index.bml, htdocs/site/bot.bml, htdocs/site/brand.bml, htdocs/site/policy.bml, views/legal/dmca.tt
In preparation for enabling HTTPS everywhere, it would be nice if all the hardcoded links are HTTPS rather than HTTP.
Along with the corresponding request at dreamwidth/dw-free, this fixes dreamwidth/dw-free#1006.
=> Replace Dreamwidth HTTP links with HTTPS

htdocs/site/suggest.bml, htdocs/stc/syndicateme.css, views/misc/about.tt
Builds on #108, since that removes references to dwscoalition.org from the suggestions page; this PR completes the job.
=> Remove references to dwscoalition.org

htdocs/site/suggest.bml
Switch the automatic "Create this suggestion as a Bugzilla ticket" to instead be "Create this suggestion as a GitHub Issue".
This _doesn't_ do anything about the tagging on new suggestions &ndash; they're still tagged as "bugzilla: unmigrated" and the like. That's easy enough to change in future, but I didn't know if y'all would want to change those tags given the existing ones are currently in use.
This doesn't do anything with the GitHub API, which I think is what @stormerider was planning in dreamwidth/dw-free#662, but instead just takes you to GitHub's new Issue page with the fields already filled out. I think that's preferable, as it means you can edit the suggestion if necessary before creating the Issue, and it also means there's no complicated faffing around with API …
=> GitHub Issue suggestions

etc/config-local.pl
Now more closely resembles the dw-free version, with
obsolete options removed and newer ones added.
Fixes dreamwidth/dw-free#1769.
=> [#1769] bring dw-nonfree config-local.pl up to date

cgi-bin/DW/Controller/Interface/Github.pm
We want to handle this using the ghi-assist python project instead.
=> Disable our /interface/github handler

views/legal/diversity.tt
This is an easy fix - the old link was already redirecting to this new link that uses HTTPS.
Fixes dreamwidth/dw-free#2071.
=> update image link to use HTTPS

htdocs/stc/tropo/tropo-purple.css, htdocs/stc/tropo/tropo-red.css
This is a companion PR to https://github.com/dreamwidth/dw-free/pull/2513, since the tropo themes aren't in dw-free.
=> Remove non-standard form control styling from non-foundation site skins

htdocs/scss/skins/tropo/tropo-purple.scss, htdocs/scss/skins/tropo/tropo-red.scss
Companion PR to https://github.com/dreamwidth/dw-free/pull/2556, which has all the spicy details. 
**Do not deploy these changes without free 2556.** They are incompatible with prior Foundation versions.
=> [#2555] Foundation usage: topbar-height has to be in rems now 

htdocs/scss/skins/tropo/_tropo-base.scss, styles/siteviews/themes.s2
This is a companion PR to https://github.com/dreamwidth/dw-free/pull/2586. (Prior to that PR, you can't pass an options hashref to the S2 siteviews version of need_res.)
There's also a fix for an unrelated IE11 bug in the Foundation version of Tropo.
=> Tropospherical: Support `s2foundation` beta

styles/sundaymorning/layout.s2, styles/transmogrified/layout.s2
This is a companion to https://github.com/dreamwidth/dw-free/pull/2595 -- since
the image shrinking CSS is in a global snippet now, it doesn't need to be
duplicated in every journal style.
=> [#2587] Remove image shrinking CSS from nonfree journal layouts

htdocs/scss/skins/tropo/_tropo-base.scss
An upcoming PR in -free lets site skins configure the base font size for journal-like content. On tropo, tradition says this should be smaller than the general base size of 16px. 
Setting this variable has no effect in the absence of the PR that consumes it, so it's safe to merge whenever.
=> Add base font size for journal pages (entry, reply)

htdocs/index.bml.text.local
It was getting re-added and re-removed every time I ran texttool.pl.
=> remove deadphrased string from index.bml.text.local

cgi-bin/DW/Hooks/CreditCard.pm
Correct information in file header and use LJ::Lang::ml instead of BML::ml.
(I think this was the only BML::ml call in dw-nonfree that wasn't in htdocs/index.bml, which is another project for another time.)
=> clean up DW::Hooks::CreditCard

htdocs/scss/skins/tropo/tropo-purple.scss, htdocs/scss/skins/tropo/tropo-red.scss
Fixes #2653 (in conjunction with https://github.com/dreamwidth/dw-free/pull/2703) 
There ended up being a straightforward explanation for why the hover colors broke. The spiral turds on mobile purple... I kind of suspect those have always been there, tbh.
<details><summary>Screenshots</summary>
"before" is what's on prod. 
Hovering on top-level nav item: 
Hovering on child item: 
Hovering on top-level item: 
Hovering on sub-item:
</details>
=> Fix header display problems in Tropospherical skins

etc/config-local.pl.example
Fixes string defined in etc/config-local.pl.example.
=> [dw-free#2764] remove bml suffix from faqbrowse links in site configs

htdocs/scss/skins/tropo/tropo-purple.scss, htdocs/scss/skins/tropo/tropo-red.scss
Changes to spacing on comment pages seem to cause an illusion that the new
`#f7f7f7` is brighter than the old `#f7f7f7`. Reduce brightness to compensate?
=> Tropos: reduce background brightness

htdocs/scss/skins/tropo/_tropo-base.scss
This has a nasty effect on print -- it ends up cutting off the content after the
first page, because the page height gets treated as the height of the container.
=> Tropos: Limit canvas border positioning hack to screen only
